/// <reference types="react-native-css/types" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by react-native-css. If you need to move or disable this file, please see the documentation.

// react-native-css@3.0.7's generated `react-native-css/types` module does not yet
// ship an ambient `*.css` module declaration (SDK 57 / nativewind 5 preview gap).
// Keep this declaration until an upstream release restores it, otherwise
// `import "*.css"` side-effect imports fail to type-check.
declare module "*.css";
